version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    versioning-strategy: increase
    labels:
      - 'pr: dependencies'
    groups:
      development-dependencies:
        dependency-type: 'development'
        exclude-patterns: ['npm-package-json-lint']
      npm-package-json-lint:
        patterns: ['npm-package-json-lint', 'npm-package-json-lint-*']

  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: monthly
    open-pull-requests-limit: 3
    labels:
      - 'pr: dependencies'
