name: Release PR

on:
  workflow_dispatch:
    inputs:
      new-version:
        description: New version to release
        required: true
        type: choice
        options: [patch, minor, major]

jobs:
  release-pr:
    uses: stylelint/.github/.github/workflows/call-release-pr.yml@f34faf02df201c8c204df4ae2543523ad54ceb07 # 0.3.1
    with:
      new-version: ${{ github.event.inputs.new-version }}
    permissions:
      contents: write
      pull-requests: write
