name: Release

on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  release:
    uses: stylelint/.github/.github/workflows/call-release.yml@f34faf02df201c8c204df4ae2543523ad54ceb07 # 0.3.1
    permissions:
      contents: write
      id-token: write
